### ISSUE TITLE
issue adding the package

### ISSUE THREAD

**Issue by lumos94** [evo-mark/vue3-snackbar#3] opened 2023-03-01 07:16 UTC
Hello,

I installed the package and configured it as per the documentation. I am getting the following error every time i  run the project.

` X [ERROR] [plugin vite:dep-scan] Failed to resolve entry for package "vue3-snackbar". The package may have incorrect main/module/exports specified in its package.json.

    node_modules/esbuild/lib/main.js:1365:21:
      1365 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///C:/laragon/www/elawform/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:21837:11)
    at resolvePackageEntry (file:///C:/laragon/www/elawform/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:21834:5)
    at tryNodeResolve (file:///C:/laragon/www/elawform/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:21572:20)
    at Context.resolveId (file:///C:/laragon/www/elawform/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:21336:28)
    at Object.resolveId (file:///C:/laragon/www/elawform/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41433:46)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolve (file:///C:/laragon/www/elawform/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41661:26)
    at async file:///C:/laragon/www/elawform/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41835:34
    at async requestCallbacks.on-resolve (C:\laragon\www\elawform\node_modules\esbuild\lib\main.js:1365:22)
    at async handleRequest (C:\laragon\www\elawform\node_modules\esbuild\lib\main.js:727:13)

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1287:20:
      1287 │       let promise = setup({
           ╵                     ^

    at setup (file:///C:/laragon/www/elawform/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41825:19)
    at handlePlugins (C:\laragon\www\elawform\node_modules\esbuild\lib\main.js:1287:21)
    at buildOrServeImpl (C:\laragon\www\elawform\node_modules\esbuild\lib\main.js:974:5)
    at Object.buildOrServe (C:\laragon\www\elawform\node_modules\esbuild\lib\main.js:780:5)
    at C:\laragon\www\elawform\node_modules\esbuild\lib\main.js:2126:17
    at new Promise (<anonymous>)
    at Object.build (C:\laragon\www\elawform\node_modules\esbuild\lib\main.js:2125:14)
    at build (C:\laragon\www\elawform\node_modules\esbuild\lib\main.js:1972:51)
    at scanImports (file:///C:/laragon/www/elawform/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41606:11)

  The plugin "vite:dep-scan" was triggered by this import

    resources/js/app.js:8:46:
      8 │ import { SnackbarService, Vue3Snackbar } from "vue3-snackbar"
        ╵                                               ~~~~~~~~~~~~~~~

`

**Comment by craigrileyuk** [comment] 2023-03-01 07:24
Apologies. There was an issue with Vite changing the file outputs. Try updating to v2.1.5

**Comment by lumos94** [comment] 2023-03-01 10:17
thank you @craigrileyuk . It works perfectly now. you should update it so the latest version is installed. I got the v2.1.3 when I npm installed it.

**Comment by throrin19** [comment] 2023-03-02 09:10
Hello, I have the same problem with version 2.1.5

**Comment by craigrileyuk** [comment] 2023-03-04 08:52
> thank you @craigrileyuk . It works perfectly now. you should update it so the latest version is installed. I got the v2.1.3 when I npm installed it.

Probably just NPM using a cached version.

**Comment by craigrileyuk** [comment] 2023-03-04 08:52
> Hello, I have the same problem with version 2.1.5

How are you installing it?

**Comment by throrin19** [comment] 2023-03-06 07:46
With npm. I check version installed in the `node_modules` and it's the 2.1.5

**Comment by craigrileyuk** [comment] 2023-03-12 23:27
Since no one else seems to be having this issue with 2.1.5 and I can't reproduce it, I'm going to close this issue.

Feel free to start a new one if you're (still) having an issue.

**Closed as completed by craigrileyuk** 2023-03-12 23:27 UTC
